src/pierror.h, src/usocket.c, src/wsocket.c
moved string constants to a seperate header file, keeping changes platofrm independent.
Please check the `wstrerror` function where there where differences in casing (that's where the initiative came from, messages just differing in casing is not platform indepedent)
=> updated error messages, less error prone, platform independent

src/options.c, src/options.h, src/udp.c
Documentation says "dontroute", "broadcast", "reuseaddr", and
"reuseport" are supported as arguments to udp:getoption(), however their
implementations were missing.
```
local udp = socket.udp()
assert( udp:setoption("broadcast", true) )
print( udp:getoption("broadcast") )
```
=> Added missing options for UDP getoption.

src/http.lua
Currently tests show that the code sends proxy info in the Host header. This can affect tomcat as it uses this information when generating pages. Test example of the header being sent out:
GET http://gato-public-st.tr.txstate.edu:80/testing-site/tests/redirect-pages/redirect-local.html HTTP/1.1
Host: 127.0.0.1:3128
TE: trailers
Connection: close, TE
User-Agent: lua 5.1, autotest
We can changed the order where the proxy updates the host and port after the headers are generated; so the actual host and port that we want to send would be put into the header. Test example of the header being sent out when we run adjustheaders before adjustproxy:
GET http://gato-public-st.tr.txstate.edu:80/testing-site/tests/redirect-pages/redirect-local.html HTTP/1.1
Host: gato-public-st.tr.txstate.edu:80
TE: …
=> Generate headers before proxy changes host and port

src/options.h, src/tcp.c
Enables the option `reuseport` to be set on TCP servers so many of them can bind to the same address.
=> Added ability to set the option `reuseport` of a tcp socket.

src/ltn12.lua, src/mbox.lua, src/tp.lua, src/url.lua
`unpack` became `table.unpack` in Lua 5.2, not available with default compilation flags in Lua 5.3.
=> Fix error in ltn12 under Lua 5.3

makefile, src/makefile
To compile on solaris some libs had to be linked. So far I was only able
to test it on OmniOS r151006 but it should work with any Solaris OS
=> Added Solaris platform

doc/socket.html, src/except.c, src/except.h, test/excepttest.lua
LuaSocket wraps error messages raised by newtry() in a table and unpacks them later so that (string) errors raised by 3rd-party code can be passed through as-is. This obviously didn't work when the 3rd-party code raised a table as an error message. This change sets a private metatable on all wrapped LuaSocket exceptions to distinguish them from 3rd-party table errors.
Since it is not yet decided whether to go with the current C implementation or rewrite the exception mechanism in Lua, this is an alternative pull request for the changes in #161 but in C instead of Lua.
See also #156 for the discussion.
=> Support table errors in LuaSockets LTN13 C implementation.

src/http.lua, src/url.lua
If a URL like `http://username:p%40ssword@server.com/` - where @ symbol in password is URL-encoded - is passed to `http.request()` method, the password is added to Authorization header as it is, leading to failed authentication response from server. Decoding the password just before adding it to the header resolves this issue. That is what this pull request does.
This should also resolve same problem in LuaSec's `https.request()` function will depends upon LuaSocket.
=> URL-decode user password before adding to authorization header.

src/makefile
It was hard to overwrite the CFLAGS/LDFLAGS settings as you had to touch the src/makefile. Now you can do something like following:
`MYCFLAGS="-m64" MYLDFLAGS="-m64" PLAT=solaris gmake all`
Now `gmake print` also shows the final setting of `CFLAGS` and `LDFLAGS`.
=> Enabled overwriting of MYCF/MYLDFlAGS

luasocket-scm-0.rockspec
Given LuaRocks support [Haiku](https://www.haiku-os.org/) as a valid platform, link the network library. I opened a PR on LuaRocks repo to get Haiku to be recoginized as a valid platform https://github.com/keplerproject/luarocks/pull/516
=> Add the lib network to the linked libs if the platform is Haiku

src/unix.c
Add backwards compatibility aliases "tcp" and "udp" for the recently renamed "stream" and "dgram" functions, as well as a wrapper function and metatable setup so that socket.unix() calls socket.unix.stream().
If desired, I can update this so that the backwards compatibility versions print a deprecation warning on first use.
=> Add backwards compatibility wrappers for socket.unix

src/url.lua
This kind of Lua could be built with this command:
```
hererocks --lua 5.3 --cflags="-DLUA_NOCVTN2S -DLUA_NOCVTS2N"
```
=> fix for Lua 5.3 built without number / string conversion

src/url.lua
percent-encode uppercase
see https://tools.ietf.org/html/rfc3986#section-6.2.2 :
"For all URIs, the hexadecimal digits within a percent-encoding
triplet (e.g., "%3a" versus "%3A") are case-insensitive and therefore
should be normalized to use uppercase letters for the digits A-F."
=> make protect_segment in url.lua rfc compliant

src/options.c
Two small temporary buffers in src/options.c were declared a bit too small to accommodate the maximum calculable size of the string that could result from sprintf(), as detected by -Wstringpop-overflow.  It turns out that 57 is the smallest number meeting this critera, silencing the GCC warning and (possibly) preventing other unpredictable or incorrect behavior.
=> src/options.c: minor buffer size issue detected by GCC 7

src/auxiliar.c, src/compat.c, src/compat.h
Provides PR #249 with a copy of `luaL_testudata` for the Lua 5.1 build case.
=> Update auxiliar.c to use luaL_testudata (#249), now with Lua 5.1 compatibility

src/mime.c
Explicitly state this case as fall through to make gcc happy.
=> Fix gcc-8.1.0 warning.

src/makefile
From #101; enable `sun_len` support on FreeBSD (regardless of calculation change).  Needs testing.
=> src/makefile: enable UNIX_HAS_SUN_LEN for FreeBSD builds

src/unixdgram.c
From #101. Allows connect() and bind() without dummy char.  Needs testing.
=> src/unixdgram.c: fix connect() and bind() on FreeBSD

doc/http.html, src/http.lua
If a `maxredirects` field is present in input table to `http.request`, it specifies an override to the hard-coded limit of `5` redirects, with a value of `false` signifying no limit.  Documentation updated.
=> Allow overriding of hard-coded redirect limit

src/compat.h
LuaJIT and LuaSocket both define new Lua APIs from Lua 5.2 (in
particular `luaL_setfuncs` and `luaL_testudata`). When linking both
statically, the one definition rule strikes and linking fails. This
commit fixes the issue by renaming the LuaSocket versions of those
functions behind the scenes using the C preprocessor.
Closes #214
=> Fix static linking problem with LuaJIT

src/makefile
Distros install the Lua include files to inconsistent paths.  Some place them in `/usr/include/lua/$(LUAV)`, others place them in `/usr/include/lua$(LUAV)`, and still others place them directly in `/usr/include` itself.
For this reason, #221 fixes some cases, but breaks others.
To accommodate, let's provide both variants.  The appropriate `CFLAG` snippets can have the `-I` prepended using multi-word substitution, which then happens to support an arbitrary number of alternatives should the situation grow worse (or should the user decide to override).
Tested on:
- Ubuntu Linux (18.04.1 LTS)
- Gentoo Linux (dev-lang/lua-5.1.5-r4)
- Raspberry Pi Ubuntu Mate (16.04.5 LTS)
Other platform testing still needed.
Also, further makefile work is probably to be expected.
=> src/makefile: support both lua/$(LUAV) and lua$(LUAV) include paths

luasocket-scm-0.rockspec
compile unixdgram.c, unixstream.c into unix.so
the unix.so in luarocks package not contain unixdgram.c and unixstream.c so that there is an error when call socket.unix
=> compile unixdgram.c, unixstream.c into unix.so

src/http.lua
In [luasec #117](https://github.com/brunoos/luasec/issues/117), it was discovered that luasocket's [http.lua](https://github.com/diegonehab/luasocket/blob/288219fd6b53ce2e709745c9918aa4c4b7f715c9/src/http.lua#L215) fails to omit the port number in the `Host:` request header when it is the default for the scheme.  While that's not improper, it is indeed rather unusual, and was problematically unexpected by at least one high-profile server in the wild.
With this change, we now only include the port number in the `Host:` header if it is not the default for the scheme, using knowledge of the default ports of schemes for which we are known to be invoked, i.e. `http` and `https`.
At the same time, compliance with [RFC 2616](https://tools.ietf.org/html/rfc2616#section-14.23) is now improved by …
=> http.lua: if default for scheme, omit port number in "Host:" header

src/http.lua
In the case of a very poor network, the connection times out and could'n get the status, then it thinks it is HTTP 0.9 and then executes receive09body function, causing the application to crash under IOS
=> Fixed an issue that was mistaken for HTTP 0.9 when timeout

src/mime.lua
The `io` package is included but never used.
=> mime.lua: Obsolete require("io")

src/udp.c, src/usocket.c
It may not be defined on some systems.
See some other comments in #242
There's a remaining issue that `AI_NUMERICSERV` from `src/udp.c` is also not defined. Not sure how to fix that one other than also commenting it out.
=> EAI_OVERFLOW, AI_NUMERICSERV: put behind #ifdef

src/makefile
See #298.  Contemporary mingw environments don't seem to want this option.
=> src/makefile: remove -DLUASOCKET_INET_PTON for mingw

test/find-connect-limit, test/tcp-getoptions, test/udp-zero-length-send, test/udp-zero-length-send-recv
In response to #297.  Work in progress.
Adding `socket =` to `require"socket"` fixes the reported error, but now I see others.
```
$ ./tcp-getoptions
options for     tcp{master}: 0x7f8a92804a28
getoption       keepalive       nil     getsockopt failed
getoption       reuseaddr       nil     getsockopt failed
getoption       tcp-nodelay     nil     getsockopt failed
lua: ./tcp-getoptions:13: bad argument #1 to 'getoption' (unsupported option `tcp-keepidle')
stack traceback:
[C]: in function 'getoption'
./tcp-getoptions:13: in function 'options'
./tcp-getoptions:23: in main chunk
[C]: ?
```
=> fix test/tcp-getoptions

src/buffer.c
This is the same issue that was fixed in MIME code in f329aae7.
Closes #331.
=> Fixes an issue with aux buffer init overwriting optional parameters in receive().

src/http.lua
If a source is specified without a content-length header, LuaSocket
sends the data in the chunked transfer coding; however, it doesn't set
the transfer-encoding header.  While I recognize that the user can set
this manually, this is a gotcha that has caught me multiple times.
RFC7230, section 3.3.3
(https://tools.ietf.org/html/rfc7230#section-3.3.3)
is clear about this; if neither content-length nor transfer-encoding
chunked are specified, the request message body length is zero.  While
some servers may ignore this, I have encountered several that follow
the RFC in this regard, most recently golang's net/http.
=> http.lua: set transfer-encoding if source and no content-length

doc/socket.html, doc/tcp.html
this is on top of the html linter PR to prevent merge conflicts, so merge that one (#358) first.
This PR documents fixes already made since #134
=> fix(docs) references to some constants added

.github/workflows/luacheck.yml
As of v0.26.0, the Luacheck repository is enabled to run *as* a GH
Action so there is no need to install Lua, LuaRocks, then the linter,
etc. Just one `uses:`.
=> ci: Utilize new upstream Luacheck Action

rockspecs/luasocket-3.0.0-1.rockspec
Closes #321.
Uses the patch I mentioned in the above issue that fixes the LuaRocks installation for my Windows system. @alerque said this needs confirmation from another Windows user and testing on *nix platforms.
=> Add windows patch to rockspec

docs/tcp.html, src/options.c, src/options.h, src/tcp.c
This makes it so that a listening socket does not become readable for
accept() until a connection has been fully established *and* started
sending something, thus the program doesn't have to wait for the first
data. This only makes sense for client-speaks-first protocols.
=> Add support for TCP_DEFER_ACCEPT

src/http.lua, test/httptest.lua
Location header can now be relative: https://httpwg.org/specs/rfc9110.html#field.location
Fix #393
=> Fix relative redirection on https

.github/workflows/build.yml, src/options.c
This PR closes #414 and provides the two changes listed below.
Note that most of the required work has taken place in relation to [gh-actions-lua](https://github.com/leafo/gh-actions-lua) and has been submitted to the upstream repository: [!35](https://github.com/leafo/gh-actions-lua/pull/35), [!37](https://github.com/leafo/gh-actions-lua/pull/37), [!38](https://github.com/leafo/gh-actions-lua/pull/38) and [gh-actions-luarocks!14](https://github.com/leafo/gh-actions-luarocks/pull/14).
In the meantime this PR changes the sources of `leafo/gh-actions-lua@v9` and `leafo/gh-actions-luarocks@v4` to `leso-kn/gh-actions-lua@v11-staging` and `hishamhm/gh-actions-luarocks@master` in [build.yml](https://github.com/lunarmodules/luasocket/pull/415/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc733 …
=> Github Actions Wokflow for Windows

src/inet.c
The documentation of getsockname() states that the port is returned as a number, which is also what the similar getpeername function does.
Closes #391
=> fix(inet): Return port as number in getsockname

src/wsocket.c
This patch fixes an issue with the current version of the library that doesn't properly report CONNRESET to the application.
This issue is 100% reproducible in my application, even though I failed to create a simple script to demonstrate it on. The issue happens when the process on the other side of the connection is killed. I bisected this issue to the commit 734cc23e1f with the following comment:
```
I am a bit unsure about the UDP fix, because it may affect
TCP as well. On UDP sockets, when a sendto fails, the next
receive/receivefrom fails with CONNRESET. I changed
sock_recv/sock_recvfrom in wsocket.c to skip the CONNRESET
from the recv/recvfrom, hoping that if the socket is TCP,
sock_waitfd will get the CONNRESET again. The tests pass,
but this should be tested more thoroughly.
``` …
=> Added a fix for properly reporting CONNRESET.

src/url.lua
Fixes #417.
How does this fix look? Simplistic but *more valid* than the current parsing I think.
=> Fix empty path parsing

src/http.lua
Fixes #385.
Needs some testing before merging.
=> fix(http): use the right protocol for proxies

src/http.lua, src/makefile, src/smtp.lua
https://github.com/love2d/love/pull/2021
=> fix typos found while building LÖVE

docs/ftp.html, docs/http.html, docs/mime.html, docs/smtp.html, docs/socket.html
addition to #426 , used search and replace this time to catch them all 🙈.
=> chore(docs): update LTN12 links

src/unixdgram.c, src/unixstream.c
Since they start with NUL byte, strlen() does the wrong thing. The Lua API can already pass the real string length, so passing that on seems the sensible thing to do.
Fixes #216
=> Pass correct path length for abstract sockets

docs/installation.html
->Removed "Installation via standard distribution" and "Directory structure" sections to avoid confusion.
->Focused on LuaRocks installation as the recommended method.
->LuaRocks is the standard way to install LuaSocket, and the manual installation details were unnecessary.
->Simplifies the documentation for new users.
->How the installation page would look like after this Pull request gets merged :
->Verified that the new instructions correctly install LuaSocket via LuaRocks.
solves issue #220
=> Improve installation instructions: Focus on LuaRocks installation

.github/workflows/build.yml
Fixed the CI build of `luasocket` for LuaJIT and OpenResty on Windows. Now, CI is working correctly on all scenarios.
1. Currently, most MinGW-w64 providers *(like the one used by GitHub)* ship a C compiler targeting the Universal C Run Time (UCRT). However, the current LuaRocks version (3.11.1) used by most GitHub Actions incorrectly detects the MSVCRT of LuaJIT and OpenResty on Windows. Thus, `MSVCRT` was set explicitly to UCRTBASE;
> [!NOTE]
> 
> This LuaRocks issue was already fixed by [https://github.com/luarocks/luarocks/commit/99c7267241e6ed0ef62123187acf7a5539a6c2db](https://github.com/luarocks/luarocks/commit/99c7267241e6ed0ef62123187acf7a5539a6c2db). However, it was merged after LuaRocks 3.11.1 release.
2. LuaRocks is unable to detect the library directory of OpenResty on …
=> CI: fix the build for LuaJIT and OpenResty on Windows

makefile, src/makefile
this will compile for MSYS2 ucrt64 if it might be helpful.
As at the moment using `luarocks` in MSYS2 ucrt64 doesn't work, this would help compiling luasocket from source.
=> add MSYS2/ucrt64 in makefile
